# Generated by Django 2.0.6 on 2018-10-08 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pedido', models.TextField()),
                ('asunto', models.TextField()),
                ('detalles', models.TextField()),
                ('prioridad', models.TextField()),
                ('sistema', models.TextField()),
                ('fecha', models.TextField(null=True)),
                ('archivo_adjunto', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_tecnico', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='pedidos.Usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tecnico_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_asignado', to='pedidos.Usuario'),
        ),
    ]
